Blockly.Msg.ADSWS1_RG_GET_RAIN_GAUGE_MM_TITLE = "ADS-WS1 24Hrs Rain Gauge";
Blockly.Msg.ADSWS1_RG_GET_RAIN_GAUGE_MM_TOOLTIP = "Read ADS-WS1 Rain Gauge Last 24 Hours (mm.)";
Blockly.Msg.ADSWS1_RG_GET_RAIN_GAUGE_MM_HELPURL = "";

Blockly.Msg.ADSWS1_RG_GET_RAIN_GAUGE_COUNTER_TITLE = "ADS-WS1 24Hrs Rain Gauge Counter";
Blockly.Msg.ADSWS1_RG_GET_RAIN_GAUGE_COUNTER_TOOLTIP = "Read ADS-WS1 Rain Gauge Counter Last 24 Hours";
Blockly.Msg.ADSWS1_RG_GET_RAIN_GAUGE_COUNTER_HELPURL = "";

Blockly.Msg.ADSWS1_RG_RESET_RAIN_GAUGE_TITLE = "ADS-WS1 Reset Rain Gauge";
Blockly.Msg.ADSWS1_RG_RESET_RAIN_GAUGE_TOOLTIP = "Reset ADS-WS1 Rain Gauge";
Blockly.Msg.ADSWS1_RG_RESET_RAIN_GAUGE_HELPURL = "";
