Blockly.Msg.atgm336h_GET_LATITUDE_TEXT_TITLE   = "ATGM336H LATITUDE";
Blockly.Msg.atgm336h_GET_LATITUDE_TEXT_TOOLTIP = "ATGM336H LATITUDE";
Blockly.Msg.atgm336h_GET_LATITUDE_TEXT_HELPURL = "";

Blockly.Msg.atgm336h_GET_LONGITUDE_TEXT_TITLE   = "ATGM336H LONGITUDE";
Blockly.Msg.atgm336h_GET_LONGITUDE_TEXT_TOOLTIP = "ATGM336H LONGITUDE";
Blockly.Msg.atgm336h_GET_LONGITUDE_TEXT_HELPURL = "";

Blockly.Msg.atgm336h_GET_YEAR_TEXT_TITLE   = "ATGM336H YEAR";
Blockly.Msg.atgm336h_GET_YEAR_TEXT_TOOLTIP = "ATGM336H YEAR";
Blockly.Msg.atgm336h_GET_YEAR_TEXT_HELPURL = "";

Blockly.Msg.atgm336h_GET_MONTH_TEXT_TITLE   = "ATGM336H MONTH";
Blockly.Msg.atgm336h_GET_MONTH_TEXT_TOOLTIP = "ATGM336H MONTH";
Blockly.Msg.atgm336h_GET_MONTH_TEXT_HELPURL = "";

Blockly.Msg.atgm336h_GET_DAY_TEXT_TITLE   = "ATGM336H DAY";
Blockly.Msg.atgm336h_GET_DAY_TEXT_TOOLTIP = "ATGM336H DAY";
Blockly.Msg.atgm336h_GET_DAY_TEXT_HELPURL = "";

Blockly.Msg.atgm336h_GET_HOUR_TEXT_TITLE   = "ATGM336H HOUR";
Blockly.Msg.atgm336h_GET_HOUR_TEXT_TOOLTIP = "ATGM336H HOUR";
Blockly.Msg.atgm336h_GET_HOUR_TEXT_HELPURL = "";

Blockly.Msg.atgm336h_GET_MINUTE_TEXT_TITLE   = "ATGM336H MINUTE";
Blockly.Msg.atgm336h_GET_MINUTE_TEXT_TOOLTIP = "ATGM336H MINUTE";
Blockly.Msg.atgm336h_GET_MINUTE_TEXT_HELPURL = "";

Blockly.Msg.atgm336h_GET_SECOND_TEXT_TITLE   = "ATGM336H SECOND";
Blockly.Msg.atgm336h_GET_SECOND_TEXT_TOOLTIP = "ATGM336H SECOND";
Blockly.Msg.atgm336h_GET_SECOND_TEXT_HELPURL = "";

Blockly.Msg.atgm336h_TX = "Tx";
Blockly.Msg.atgm336h_RX = "Rx";