Blockly.Msg.PLANTOWER_GET_PM2_5_TITLE = "PLANTOWER PM2.5";
Blockly.Msg.PLANTOWER_GET_PM2_5_TOOLTIP = "Read PLANTOWER PM2.5";
Blockly.Msg.PLANTOWER_GET_PM2_5_HELPURL = "";

Blockly.Msg.PLANTOWER_GET_PM10_TITLE = "PLANTOWER PM10";
Blockly.Msg.PLANTOWER_GET_PM10_TOOLTIP = "Read PLANTOWER PM10";
Blockly.Msg.PLANTOWER_GET_PM10_HELPURL = "";

Blockly.Msg.PLANTOWER_PM_TX = "Tx";
Blockly.Msg.PLANTOWER_PM_RX = "Rx";

Blockly.Msg.PLANTOWER_IS_ERROR_TITLE = "PLANTOWER Check Error";
Blockly.Msg.PLANTOWER_IS_ERROR_TOOLTIP = "Check PLANTOWER error status";
Blockly.Msg.PLANTOWER_IS_ERROR_HELPURL = "";

Blockly.Msg.PLANTOWER_GET_ERROR_COUNT_TITLE = "PLANTOWER Get Error Count";
Blockly.Msg.PLANTOWER_GET_ERROR_COUNT_TOOLTIP = "Get number of PLANTOWER error count";
Blockly.Msg.PLANTOWER_GET_ERROR_COUNT_HELPURL = "";

Blockly.Msg.PLANTOWER_GET_ERROR_CLEAR_COUNT_TITLE = "PLANTOWER Get Error Clear Count";
Blockly.Msg.PLANTOWER_GET_ERROR_CLEAR_COUNT_TOOLTIP = "Get number of PLANTOWER error clear count";
Blockly.Msg.PLANTOWER_GET_ERROR_CLEAR_COUNT_HELPURL = "";
