#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

# [build]
# PATH=$PATH:/home/user/build/esp-idf-v3.1/xtensa-esp32-elf/bin IDF_PATH=/home/user/build/esp-idf-v3.1 make component-blink_static-build

# [clean]
# PATH=$PATH:/home/user/build/esp-idf-v3.1/xtensa-esp32-elf/bin IDF_PATH=/home/user/build/esp-idf-v3.1 make component-blink_static-clean

EXTRA_COMPONENT_DIRS := blink_static

include $(IDF_PATH)/make/project.mk
